server:
  port: ${DEMO_PORT:8080}

spring:
  application:
    name: sal-demo
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    virtual-host: ${RMQ_VHOST:/}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PASS:guest}

sal:
  command-bus:
    adapter-name: ${DEMO_ADAPTER_NAME:JavaDemoAdapter}
    default-timeout: 120s
    concurrency: "5"

demo:
  adapter-name: ${DEMO_ADAPTER_NAME:JavaDemoAdapter}
  handle-commands: ${DEMO_HANDLE_COMMANDS:}
  per-command-queues: ${DEMO_PER_COMMAND_QUEUES:true}
